services:
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    entrypoint: ["pnpm", "dev"]
    tty: true
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./app/backend:/app/backend
    ports:
      - 5000:5000
      - 5001:5001
    entrypoint: ["python", "main.py"]
    tty: true