services:
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3100:3100
    entrypoint: ["pnpm", "dev"]
    tty: true
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - MEDIAPIPE_DISABLE_GPU=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./app/backend:/app/backend
    ports:
      - 5100:5100
      - 5101:5101
    entrypoint: ["python", "src/main.py"]
    tty: true